apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.syncapi.name }}-config-vm
  namespace: {{ .Release.Namespace | quote }}
  labels: {{- include "corezoid.labels.standard" . | nindent 4 }}
    app.kubernetes.io/component: {{ .Values.syncapi.name }}
  annotations:
    {{- include "corezoid.provisoner.configmap" . | nindent 4 }}
data:
  vm.args: |
    ## Name of the node
    -name corezoid_api_sync@${IPNODEDOMAIN}

    ## Cookie for distributed erlang
    -setcookie ${NODE_COOKIE}
    +sbwt none

    +S ${SCHEDULERS}
