apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.capi.name }}-config-vm
  namespace: {{ .Release.Namespace | quote }}
  labels: {{- include "corezoid.labels.standard" . | nindent 4 }}
    app.kubernetes.io/component: {{ .Values.capi.name }}
  annotations:
    {{- include "corezoid.provisoner.configmap" . | nindent 4 }}
data:
  vm.args: |
    ## Name of the node
    -name capi@${IPNODEDOMAIN}

    ## Cookie for distributed erlang
    -setcookie ${NODE_COOKIE}

    ## Mode without input and shell starting
    #-noinput
    #-detached

    ## Max tables per VM
    -env ERL_MAX_ETS_TABLES 100000
    ## Max ports per VM
    -env ERL_MAX_PORTS 165000

    ## Mode without input and shell starting
    #-noinput
    #-detached

    ## Max tables per VM
    -env ERL_MAX_ETS_TABLES 100000
    ## Max ports per VM
    -env ERL_MAX_PORTS 165000

    -mnesia dir '"mnesia"'

    ## Heartbeat management; auto-restarts VM if it dies or becomes unresponsive
    ## (Disabled by default..use with caution!)
    ##-heart

    ## Enable kernel poll and a few async threads
    +K true
    +A 500

    ## Increase number of concurrent ports/sockets
    ##-env ERL_MAX_PORTS 4096

    ## Tweak GC to run more often
    ##-env ERL_FULLSWEEP_AFTER 10
    +sbwt none
    +S ${SCHEDULERS}
