---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.mult.name }}-service
  namespace: {{ .Release.Namespace | quote }}
  labels: {{- include "corezoid.labels.standard" . | nindent 4 }}
    app.kubernetes.io/component: {{ .Values.mult.name }}
spec:
  selector: {{- include "corezoid.labels.matchLabels" . | nindent 4 }}
    app.kubernetes.io/component: {{ .Values.mult.name }}
  ports:
  - name: mult
    protocol: TCP
    port: {{ .Values.mult.service.multPort | default 80 }}
    targetPort: mult
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.mult.name }}-service-node
  namespace: {{ .Release.Namespace | quote }}
  labels: {{- include "corezoid.labels.standard" . | nindent 4 }}
    app.kubernetes.io/component: {{ .Values.mult.name }}
spec:
  selector: {{- include "corezoid.labels.matchLabels" . | nindent 4 }}
    app.kubernetes.io/component: {{ .Values.mult.name }}
  type: NodePort
  ports:
    - name: mult
      protocol: TCP
      port: {{ .Values.mult.service.multPort | default 80 }}
      targetPort: mult