apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.appName }}-config
data:
  .htpasswd: |-
    # Managed by helm
    {{ range $key, $value := .Values.global.store_dumps.base_auth }}
    {{ $value }}
    {{ end }}
  default.conf: |-
    server {
      listen       80;
      server_name {{ .Values.global.store_dumps.subdomain }}.{{ .Values.global.domain }} ;
      root /var/www;

      location / {
          autoindex on;
          auth_basic "Restricted";                           #For Basic Auth
          auth_basic_user_file /etc/nginx/conf.d/.htpasswd;  #For Basic Auth
      }

      # download
      autoindex on;
      autoindex_exact_size off;
      autoindex_localtime on;

    }
