apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.merchant.name }}-callback-properties
  namespace: {{ .Release.Namespace | quote }}
  labels: {{- include "corezoid.labels.standard" . | nindent 4 }}
    app.kubernetes.io/component: {{ .Values.merchant.name }}
  annotations:
    {{- include "corezoid.provisoner.configmap" . | nindent 4 }}
data:
  callback.properties: |
    app.synchronisationEnabled=true
    app.callbackProperties[0].url=https://{{ .Values.capi.subdomain }}.{{ .Values.global.domain }}/api/2/json/plugins/mapi
    app.callbackProperties[0].retryCount=3
    app.callbackProperties[0].retryTimeoutMillisec=5000
    app.callbackProperties[1].url=https://api-adm.sender/merchant_api/sync
    app.callbackProperties[1].retryCount=3
    app.callbackProperties[1].retryTimeoutMillisec=5000

