---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.merchant.name }}-secret
  namespace: {{ .Release.Namespace | quote }}
  labels: {{- include "corezoid.labels.standard" . | nindent 4 }}
    app.kubernetes.io/component: {{ .Values.merchant.name }}
  annotations:
    {{- include "corezoid.provisoner.secrets" . | nindent 4 }}
type: Opaque
data:
  MERCHANT_SECRET: {{ .Values.merchant.merchant_secret | b64enc | quote }}
  MERCHANT_LOGIN: {{ .Values.merchant.merchant_login | b64enc | quote }}
