{{- if .Values.global.capi.auth_providers_enable  }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.global.capi.capi_saml_secret_name | default "capi-saml-secret" }}
  labels:
    app: {{ .Values.global.product }}
    tier: "capi"
type: Opaque
data:
  {{- $root := . -}}
  {{- range $path, $bytes := .Files.Glob "files/GoogleIDPMetadata.xml" }}
  GoogleIDPMetadata.xml: '{{ $root.Files.Get $path | b64enc }}'
  {{- end }}
  {{- if .Values.global.capi.capi_saml_secret_support  }}
  {{- $root := . -}}
  {{- range $path, $bytes := .Files.Glob "files/GoogleIDPMetadataSupport.xml" }}
  GoogleIDPMetadataSupport.xml: '{{ $root.Files.Get $path | b64enc }}'
  {{- end }}
  {{- end }}
{{- end }}



