---
apiVersion: v1
kind: Secret
metadata:
  name: license-share-new
  namespace: {{ .Release.Namespace | quote }}
  labels: {{- include "corezoid.labels.standard" . | nindent 4 }}
  annotations:
    {{- include "corezoid.provisoner.secrets" . | nindent 4 }}
type: Opaque
data:
  {{- $root := . -}}
  {{- range $path, $bytes := .Files.Glob "license/corezoid_license" }}
  corezoid_license: '{{ $root.Files.Get $path | b64enc }}'
{{- end }}
