{{- if .Values.ingress.enabled }}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: corezoid-{{ .Release.Namespace }}-ingress
  namespace: {{ .Release.Namespace | quote }}
  labels: {{- include "corezoid.labels.standard" . | nindent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
  {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  rules:
    - host: {{ .Values.capi.subdomain }}.{{ .Values.global.domain }}
      http:
        paths:
          - path: /api/?/upload*
            backend:
              serviceName: {{ .Values.mult.name }}-service-node
              servicePort: {{ .Values.mult.service.multPort | default 80 }}
          - path: /api/?/copy*
            backend:
              serviceName: {{ .Values.mult.name }}-service-node
              servicePort: {{ .Values.mult.service.multPort | default 80 }}
          - path: /user_downloads*
            backend:
              serviceName: {{ .Values.mult.name }}-service-node
              servicePort: {{ .Values.mult.service.multPort | default 80 }}
          - path: /api/?/download*
            backend:
              serviceName: {{ .Values.mult.name }}-service-node
              servicePort: {{ .Values.mult.service.multPort | default 80 }}
          - path: /api/*
            backend:
              serviceName: {{ .Values.capi.name }}-service-node
              servicePort: {{ .Values.capi.service.capiPort | default 80 }}
          - path: /auth/*
            backend:
              serviceName: {{ .Values.capi.name }}-service-node
              servicePort: {{ .Values.capi.service.capiPort | default 80 }}
          - path: /system
            backend:
              serviceName: {{ .Values.capi.name }}-service-node
              servicePort: {{ .Values.capi.service.capiPort | default 80 }}
          - backend:
              serviceName: {{ .Values.webadm.name }}-service
              servicePort: {{ .Values.webadm.service.port | default 80 }}
    - host: {{ .Values.websuperadm.subdomain}}.{{ .Values.global.domain }}
      http:
        paths:
          - backend:
              serviceName: {{ .Values.websuperadm.name }}-service
              servicePort: {{ .Values.websuperadm.service.port | default 80 }}
    - host: {{ .Values.syncapi.subdomain}}.{{ .Values.global.domain }}
      http:
        paths:
          - backend:
              serviceName: {{ .Values.syncapi.name }}-service
              servicePort: {{ .Values.syncapi.service.syncapiPort | default 80 }}
    {{- if .Values.sa.enabled }}
    - host: {{ .Values.sa_web.subdomain}}.{{ .Values.global.domain }}
      http:
        paths:
          - backend:
              serviceName: single-account-web
              servicePort: 80
  {{- end }}
  {{- if .Values.ingress_tls }}
  tls:
    - hosts:
        - {{ .Values.capi.subdomain}}.{{ .Values.global.domain }}
        - {{ .Values.websuperadm.subdomain}}.{{ .Values.global.domain }}
        - {{ .Values.syncapi.subdomain}}.{{ .Values.global.domain }}
        {{- if .Values.sa.enabled }}
        - {{ .Values.sa_web.subdomain}}.{{ .Values.global.domain }}
        {{- end }}ingress_tls
      secretName: tls-{{- include "corezoid.names.name" . }}-test
{{- end }}
{{- end }}
