{{- if  eq .Values.externalPostgresql.postgres_schema.version "5.7.0" }}
apiVersion: v1
kind: Pod
metadata:
  name: postgres-post-install
  annotations:
  {{- include "corezoid.provisoner.postinstall" . | nindent 4 }}
  labels:
    tier: postgres
spec:
  containers:
    - image: docker-hub.middleware.biz/public/postgres:9.6.2-alpine
      imagePullPolicy: {{ .Values.global.pullPolicy | default "IfNotPresent" }}
      name: postgres-taskarchive-cron
      command:
        - sh
        - -c
        - |
          echo  "{{ template "corezoid.postgres.host" . }}:*:*:{{ template "corezoid.postgres.rootname" . }}:$POSTGRES_DBSUPERUSERPWD" > ~/.pgpass; chmod 0600 ~/.pgpass;
          psql -h {{ template "corezoid.postgres.host" . }} -U {{ template "corezoid.postgres.rootname" . }} -d conveyor -Atc "alter table IF EXISTS projects DROP column IF EXISTS owner_id;";
          psql -h {{ template "corezoid.postgres.host" . }} -U {{ template "corezoid.postgres.rootname" . }} -d conveyor -Atc "alter table IF EXISTS aliases drop constraint IF EXISTS temp_aliases_short_name_company_id_project_id;";
      securityContext:
        runAsUser: 70
      env:
        - name: SHARD_COUNT
          value: '{{ .Values.externalPostgresql.shards_count }}'
      envFrom:
        - secretRef:
            name: {{ template "common.names.fullname" . }}-postgres-root
  restartPolicy: Never
  terminationGracePeriodSeconds: 0


{{- end }}
