apiVersion: batch/v1
kind: Job
metadata:
  name: postgres-init-database
  labels:
    tier: postgres-job
  annotations:
    {{- include "corezoid.provisoner.job" . | nindent 4 }}
spec:
  template:
    metadata:
      name: postgres-init-database
      labels:
        tier: postgres-job
    spec:
      restartPolicy: OnFailure
      containers:
        - image: "docker-hub.middleware.biz/public/pg_schema:{{ .Values.externalPostgresql.postgres_schema.version }}"
          imagePullPolicy: {{ .Values.global.imagePullPolicy | default "IfNotPresent" }}
          name: postgres-initdb
          command: ["/bin/sh"]
          args: ["-c", "/postgres-schema-versioner/run.sh"]
          env:
            - name: SCHEMA_VERSION
              value: {{ .Values.externalPostgresql.postgres_schema.version }}
            - name: SHARD_COUNT
              value: '{{ .Values.externalPostgresql.shards_count }}'
          envFrom:
            - secretRef:
                name: {{ template "common.names.fullname" . }}-postgres-root
