{{- if (include "corezoid.postgres.createSecret" .) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "common.names.fullname" . }}-postgres
  labels: {{- include "common.labels.standard" . | nindent 4 }}
    tier: "postgres"
  annotations:
    {{- include "corezoid.provisoner.secrets" . | nindent 4 }}
type: Opaque
data:
  POSTGRES_DBHOST: {{ include "corezoid.postgres.host" . | b64enc | quote }}
  POSTGRES_DBUSER: {{ include "corezoid.postgres.username" . | b64enc | quote }}
  POSTGRES_DBPWD: {{ .Values.externalPostgresql.postgresqlPassword | b64enc | quote }}
  POSTGRES_DBPORT: {{ include "corezoid.postgres.port" . | b64enc | quote }}
  SPRING_DATASOURCE_URL: {{ include "corezoid.postgres.host" . | b64enc | quote }}
  SPRING_DATASOURCE_USERNAME: {{ include "corezoid.postgres.username" . | b64enc | quote }}
  SPRING_DATASOURCE_PASSWORD: {{ .Values.externalPostgresql.postgresqlPassword | b64enc | quote }}
{{- end }}
---
{{- if (include "corezoid.postgres.createSecret" .) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "common.names.fullname" . }}-postgres-root
  labels: {{- include "common.labels.standard" . | nindent 4 }}
    tier: "postgres"
  annotations:
  {{- include "corezoid.provisoner.secrets" . | nindent 4 }}
type: Opaque
data:
  POSTGRES_DBHOST: {{ include "corezoid.postgres.host" . | b64enc | quote }}
  POSTGRES_DBSUPERUSER: {{ include "corezoid.postgres.rootname" . | b64enc | quote }}
  POSTGRES_DBSUPERUSERPWD: {{ .Values.externalPostgresql.postgresqlPostgresPassword | b64enc | quote }}
  POSTGRES_DBPORT: {{ include "corezoid.postgres.port" . | b64enc | quote }}
  postgres-password: {{ .Values.externalPostgresql.postgresqlPassword | b64enc | quote }}
  POSTGRES_DBUSER: {{ include "corezoid.postgres.username" . | b64enc | quote }}
  POSTGRES_DBPWD: {{ .Values.externalPostgresql.postgresqlPassword | b64enc | quote }}
  SPRING_DATASOURCE_URL: {{ include "corezoid.postgres.host" . | b64enc | quote }}
  SPRING_DATASOURCE_USERNAME: {{ include "corezoid.postgres.username" . | b64enc | quote }}
  SPRING_DATASOURCE_PASSWORD: {{ .Values.externalPostgresql.postgresqlPassword | b64enc | quote }}
{{- end }}
